admin_atom_cms_pages:
    resource: "@AtomCmsBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /

atom_cms_page:
    defaults: { _controller: AtomCmsBundle:Page:page }
    pattern: /{url}
