<?php

namespace NordUa\AtomCmsBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;


/**
 * CmsPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsPageRepository extends DocumentRepository
{

}